---
title: "Fitting BR displays with multiple contrast levels"
author: "Alexander (Sasha) Pastukhov"
date: "23 1 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(loo)
library(MASS)
library(purrr)
library(readr)
library(rstan)
library(tidyr)
```

```{r Tabula rasa}
rm(list = ls())
```

```{r settings}
file <- "Contrasts.csv"
taus <- c(0.9, 30)
```

## History choice

Select which history to use (`history_to_use` variable). By default, we used "Same" history, _i.e._, history computed for the percept that becomes dominant.

```{r history settings}
history_to_use <- "Same"
history_variants <- c("Same", "Other")
history_to_exclude <- setdiff(history_variants, c(history_to_use))
```


## Importing data

```{r import}
reports <- read_csv(fs::path("Data with History", file),
                    col_types = cols(Observer = col_character(),
                                     Contrast = col_double(),
                                     State = col_double(),
                                     Time = col_double(),
                                     Duration = col_double(),
                                     HistorySame = col_double(),
                                     HistoryOther = col_double(),
                                     Tau = col_double())) %>%
  
  filter(Tau %in% taus) %>%
  dplyr::select(-one_of(stringr::str_c("History", history_to_exclude))) %>%
  dplyr::rename(History = !!stringr::str_c("History", history_to_use)) %>%
  # na.omit() %>%
  ungroup() %>%

  # adding group and unique observer ID
  mutate(Group = "Contrasts",
         Observer = as.factor(Observer),
         iObserver= as.integer(Observer)) %>%
  
  # centering contrast at 0.5 to match other conditions
  mutate(Contrast = Contrast - 0.5) %>%
  
  # converting contrast to index (for faster sampling)
  mutate(fContrast = as.factor(Contrast), 
         iContrast = as.integer(fContrast))

if (history_to_use == "Same") {
  reports$History <- 1 - reports$History
}

# centering history based on its median value
reports <-
  reports %>%
  group_by(Tau, Observer) %>%
  mutate(cHistory = History - median(History, na.rm=TRUE))

# putting history per tau in a separate column
reports_wide <-
  reports %>%
  ungroup() %>%
  mutate(Observer = as.factor(Observer), 
         iObserver = as.integer(Observer)) %>%
  dplyr::select(-History) %>%
  tidyr::pivot_wider(names_from = Tau, values_from = cHistory) %>%
  na.omit()

  # extracting history into separate matrix
history_matrix <-
  reports_wide %>%
  select_at((ncol(.)-length(taus)+1) : ncol(.)) %>%
  as.matrix()

data_for_stan <- list(
  rowN = nrow(reports_wide),
  participantsN = max(reports_wide$iObserver),
  timescalesN = ncol(history_matrix),
  contrastN = length(unique(reports_wide$Contrast)),

  iParticipant = reports_wide$iObserver,
  Participant = levels(reports_wide$Observer),

  Duration = reports_wide$Duration,
  History = history_matrix,
  
  iContrast = reports_wide$iContrast,
  Contrast = sort(unique(reports_wide$Contrast)),
  
  Tau = taus,
  Group = reports_wide$Group[1]
)

```


```{stan output.var="gamma_model"}
data{
  int<lower=1> rowN;          // number of rows in the table
  int<lower=1> participantsN; // number of participants
  int<lower=1> timescalesN;   // number of timescales
  int<lower=1> contrastN;     // number of contrasts

  int<lower=1> iParticipant[rowN];  // participant 

  real<lower=0> Duration[rowN]; // duration of the current percept
  matrix[rowN, timescalesN] History; // history before current percept onset
  int<lower=0> iContrast[rowN];
  real Contrast[contrastN];
}
parameters{
  // --- intercepts, fully independent ---
  vector[participantsN] aShape;
  vector[participantsN] aScale;

  // --- main effect of the history, hierarchical ---
  // participants
  row_vector[timescalesN] bShape_History[participantsN];
  row_vector[timescalesN] bScale_History[participantsN];
  
  // group
  vector[timescalesN] bShape_History_Mu;
  vector<lower=0>[timescalesN] bShape_History_Sigma;
  vector[timescalesN] bScale_History_Mu;
  vector<lower=0>[timescalesN] bScale_History_Sigma;
  
  
  // --- main effect of the contrast, hierarchical ---
  // participants
  vector[participantsN] bShape_Contrast;
  vector[participantsN] bScale_Contrast;
  
  // population
  real bShape_Contrast_Mu;
  real<lower=0> bShape_Contrast_Sigma;
  real bScale_Contrast_Mu;
  real<lower=0> bScale_Contrast_Sigma;
}
transformed parameters{
  real shapeNonHistory[participantsN, contrastN];
  real scaleNonHistory[participantsN, contrastN];

  vector<lower=0>[rowN] shape;
  vector<lower=0>[rowN] scale;

  // computing participant x contrast dependent values: 
  for(iP in 1:participantsN){
    for(iC in 1:contrastN){
      shapeNonHistory[iP, iC] = aShape[iP] + bShape_Contrast[iP] * Contrast[iC];
      scaleNonHistory[iP, iC] = aScale[iP] + bScale_Contrast[iP] * Contrast[iC];
    }
  }

  for(iRow in 1:rowN){
    shape[iRow] = exp(shapeNonHistory[iParticipant[iRow], iContrast[iRow]] + 
                      sum(bShape_History[iParticipant[iRow]] .* History[iRow]));
    scale[iRow] = exp(scaleNonHistory[iParticipant[iRow], iContrast[iRow]] + 
                      sum(bScale_History[iParticipant[iRow]] .* History[iRow]));
  }
}
model {
  // --- intercepts, fully independent ---
  aShape ~ normal(0, 10);
  aScale ~ normal(0, 10);

  // --- main effect of the history, population ---
  bShape_History_Mu ~ normal(0.0, 1.0);
  bShape_History_Sigma ~ cauchy(0, 10);
  bScale_History_Mu ~ normal(0, 1);
  bScale_History_Sigma ~ cauchy(0, 10);

  // --- main effect of the contrast ---
  // population
  bShape_Contrast_Mu ~ normal(0, 1);
  bShape_Contrast_Sigma ~ cauchy(0, 10);
  bScale_Contrast_Mu ~ normal(0, 1);
  bScale_Contrast_Sigma ~ cauchy(0, 10);

  // main effect of the contrast, participants
  bShape_Contrast ~ normal(bShape_Contrast_Mu, bShape_Contrast_Sigma);
  bScale_Contrast ~ normal(bScale_Contrast_Mu, bScale_Contrast_Sigma);
  
  // parameters for each timescale
  for(iT in 1:timescalesN){
    for(iP in 1:participantsN) {
      // main effect of history, participants
      bShape_History[iP][iT] ~ normal(bShape_History_Mu[iT],
                                      bShape_History_Sigma[iT]);
      bScale_History[iP][iT] ~ normal(bScale_History_Mu[iT],
                                      bScale_History_Sigma[iT]);
     }
  }

  Duration ~ gamma(shape, inv(scale));
}
generated quantities{
  vector[rowN] log_lik;
  for (iRow in 1:rowN){
    log_lik[iRow] = gamma_lpdf(Duration[iRow] | shape[iRow], inv(scale[iRow]));
  }
}
```


## Fitting model
```{r putting models in a single tibble}
model_fit <- rstan::sampling(gamma_model,
                             include=FALSE,
                             control = list(adapt_delta=0.95, max_treedepth=15),
                             pars=c("shape", "scale"),
                             cores = future::availableCores(),
                             data = data_for_stan)

save(model_fit, file="Fits/Contrasts.Rdata")

rstan::check_hmc_diagnostics(model_fit)

posterior <- rstan::extract(model_fit)
save(posterior, data_for_stan, file="Posterior samples/Contrasts.RData")
```
